INSERT INTO algorithm_problem
(problem_code, title, statement, difficulty, tags, constraints_json, evaluation_rubric_json, follow_up_templates_json, enabled)
VALUES
('two-sum', '两数之和', '给定整数数组 nums 和目标值 target，请说明如何找到和为 target 的两个元素下标。', 'easy', 'array,hash',
 JSON_ARRAY('数组长度至少为 2', '恰好存在一个有效答案', '不能重复使用同一元素'),
 JSON_ARRAY('能从双重循环推导到哈希表', '说明先查后存以避免使用自身', '时间 O(n)，空间 O(n)'),
 JSON_ARRAY('如果存在多组答案怎么办', '如果数组有序如何优化空间'), 1),
('valid-parentheses', '有效括号', '给定只包含括号字符的字符串，请判断括号是否有效匹配。', 'easy', 'stack,string',
 JSON_ARRAY('括号包含 ()[]{}', '空字符串视为有效'),
 JSON_ARRAY('使用栈保存待匹配左括号', '遇到右括号检查栈顶', '处理栈提前为空和最终非空'),
 JSON_ARRAY('如果括号类型可以动态扩展怎么办'), 1),
('reverse-linked-list', '反转链表', '给定单链表头节点，请说明如何反转链表并返回新头节点。', 'easy', 'linked-list,pointer',
 JSON_ARRAY('允许空链表', '要求原地反转'),
 JSON_ARRAY('维护 prev、current、next', '修改指针前保存 next', '时间 O(n)，空间 O(1)'),
 JSON_ARRAY('如何递归实现', '如何反转指定区间'), 1),
('binary-tree-level-order', '二叉树层序遍历', '给定二叉树根节点，请按层返回节点值。', 'medium', 'tree,bfs,queue',
 JSON_ARRAY('允许空树', '每层结果独立保存'),
 JSON_ARRAY('使用队列进行 BFS', '每轮固定读取当前层队列长度', '时间 O(n)，空间 O(w)'),
 JSON_ARRAY('如何改成从底向上输出', '如何输出每层平均值'), 1),
('longest-substring', '无重复字符的最长子串', '给定字符串，请求不含重复字符的最长连续子串长度。', 'medium', 'string,sliding-window,hash',
 JSON_ARRAY('子串必须连续', '字符串可能为空'),
 JSON_ARRAY('滑动窗口维护无重复区间', '记录字符最近位置', '左边界不能后退'),
 JSON_ARRAY('字符集很小时如何优化空间'), 1),
('merge-intervals', '合并区间', '给定若干闭区间，请合并所有重叠区间。', 'medium', 'array,sort,interval',
 JSON_ARRAY('输入顺序任意', '端点相等视为重叠'),
 JSON_ARRAY('先按左端点排序', '比较当前右端点与下一左端点', '说明排序带来的 O(n log n)'),
 JSON_ARRAY('输入已按左端点有序时复杂度如何变化'), 1),
('lru-cache', 'LRU 缓存', '设计支持 O(1) get 和 put 的 LRU 缓存，并说明核心数据结构。', 'medium', 'hash,linked-list,design',
 JSON_ARRAY('容量为正整数', '访问和更新都算最近使用'),
 JSON_ARRAY('哈希表定位节点', '双向链表维护新旧顺序', '处理更新、淘汰和容量边界'),
 JSON_ARRAY('并发访问时如何保证正确性'), 1),
('top-k-frequent', '前 K 个高频元素', '给定整数数组和 k，请返回出现频率最高的 k 个元素。', 'medium', 'hash,heap,bucket',
 JSON_ARRAY('答案不要求顺序', 'k 合法'),
 JSON_ARRAY('哈希统计频次', '使用小顶堆或桶排序', '比较两种方案的复杂度和适用条件'),
 JSON_ARRAY('数据流无法一次放入内存时怎么办'), 1),
('lowest-common-ancestor', '二叉树最近公共祖先', '给定普通二叉树中的两个节点，请寻找它们的最近公共祖先。', 'medium', 'tree,dfs,recursion',
 JSON_ARRAY('两个节点都存在', '节点值可能重复，应比较节点身份'),
 JSON_ARRAY('递归返回子树命中信息', '左右均命中时当前节点为答案', '覆盖一个节点是另一个节点祖先的情况'),
 JSON_ARRAY('如果是二叉搜索树如何利用有序性'), 1),
('coin-change', '零钱兑换', '给定不同面额硬币和总金额，请求凑成该金额所需的最少硬币数，不可达返回 -1。', 'hard', 'dynamic-programming',
 JSON_ARRAY('每种硬币数量不限', '金额可能为 0'),
 JSON_ARRAY('定义 dp[x] 为凑成 x 的最少数量', '正确初始化不可达状态', '说明转移顺序和复杂度'),
 JSON_ARRAY('如果每种硬币数量有限如何修改'), 1)
ON DUPLICATE KEY UPDATE
 title=VALUES(title), statement=VALUES(statement), difficulty=VALUES(difficulty), tags=VALUES(tags),
 constraints_json=VALUES(constraints_json), evaluation_rubric_json=VALUES(evaluation_rubric_json),
 follow_up_templates_json=VALUES(follow_up_templates_json), enabled=VALUES(enabled);
