INSERT INTO question_card
(card_code, module, difficulty, main_question, key_points, common_mistakes, followups, scenario_followups, scoring_rubric, tags, enabled)
VALUES
('java-hashmap-structure', 'Java', 'medium', 'HashMap 的底层结构是什么？JDK 1.8 相比 JDK 1.7 有哪些变化？',
 '["数组+链表+红黑树","JDK 1.8 引入红黑树","链表长度和容量阈值触发树化","扰动函数与哈希冲突处理"]',
 '["只说数组加链表","不知道树化条件","把 HashMap 说成线程安全"]',
 '["为什么链表过长要转红黑树？","HashMap 为什么线程不安全？","ConcurrentHashMap 和 HashMap 的区别是什么？"]',
 '["高并发统计场景下能不能直接用 HashMap？为什么？"]',
 '["结构准确性","JDK 版本差异","并发风险意识","场景表达"]',
 'collection,hash,concurrency', 1),

('java-equals-hashcode', 'Java', 'easy', 'equals 和 hashCode 有什么关系？为什么重写 equals 通常也要重写 hashCode？',
 '["equals 相等对象 hashCode 必须相等","hashCode 相等不代表 equals 相等","HashMap/HashSet 依赖两者定位和比较","违反约定会导致集合行为异常"]',
 '["认为 hashCode 相等就一定是同一对象","只从语法角度解释","忽略集合场景"]',
 '["如果只重写 equals 不重写 hashCode 会发生什么？","HashSet 如何判断元素重复？"]',
 '["自定义 User 对象作为 HashMap key 时要注意什么？"]',
 '["契约理解","集合场景","反例说明"]',
 'object,collection,hash', 1),

('java-threadpool-params', 'Java', 'medium', '线程池的核心参数有哪些？线程池提交任务后的执行流程是什么？',
 '["corePoolSize","maximumPoolSize","workQueue","keepAliveTime","RejectedExecutionHandler","先核心线程再队列再最大线程再拒绝"]',
 '["只背参数不讲执行流程","忽略队列类型影响","不知道拒绝策略"]',
 '["为什么不建议使用 Executors.newFixedThreadPool？","有界队列和无界队列有什么风险？"]',
 '["如果接口突然流量变大，你会怎么配置线程池？"]',
 '["参数完整性","执行流程","风险意识","调优场景"]',
 'thread,pool,concurrency', 1),

('java-volatile', 'Java', 'medium', 'volatile 关键字能保证什么？不能保证什么？',
 '["保证可见性","禁止指令重排序","不能保证复合操作原子性","底层与内存屏障相关"]',
 '["认为 volatile 能完全替代锁","没有区分可见性和原子性","不会举例说明 i++ 问题"]',
 '["volatile 为什么不能保证 i++ 的线程安全？","单例双重检查为什么要加 volatile？"]',
 '["状态标记位适合用 volatile 吗？为什么？"]',
 '["内存语义","原子性边界","典型场景"]',
 'jmm,volatile,concurrency', 1),

('java-exception', 'Java', 'easy', 'Java 中 checked exception 和 unchecked exception 有什么区别？实际开发中如何选择？',
 '["checked exception 编译期强制处理","unchecked exception 继承 RuntimeException","业务异常通常用 unchecked","异常要表达可恢复性和调用方责任"]',
 '["只背继承关系","不知道实际项目中如何设计业务异常","滥用 Exception"]',
 '["为什么很多 Spring 项目使用运行时业务异常？","异常信息应该暴露给前端吗？"]',
 '["接口参数不合法时你会抛什么异常？"]',
 '["概念区分","工程实践","异常边界"]',
 'exception,engineering', 1),

('mysql-index-principle', 'MySQL', 'medium', 'MySQL 索引为什么通常使用 B+ 树？',
 '["B+ 树高度低","非叶子节点存 key 提高扇出","叶子节点链表适合范围查询","磁盘 IO 友好"]',
 '["只说查询快","把 B 树和 B+ 树混淆","忽略范围查询"]',
 '["为什么不用红黑树？","B+ 树范围查询为什么更方便？"]',
 '["一个慢查询加索引后为什么仍然可能慢？"]',
 '["数据结构理解","磁盘 IO 意识","范围查询场景"]',
 'index,bplus-tree,storage', 1),

('mysql-leftmost-prefix', 'MySQL', 'medium', '联合索引的最左前缀原则是什么？哪些情况会导致索引失效？',
 '["联合索引按字段顺序建立有序结构","查询要从最左列开始连续命中","范围查询后续列可能无法继续利用","函数/隐式转换/前置模糊可能失效"]',
 '["只背最左匹配不讲原因","忽略范围查询影响","不会结合 explain 判断"]',
 '["where a=? and c=? 能否完整使用 (a,b,c) 索引？","like \"%abc\" 为什么难以走索引？"]',
 '["订单表按 user_id、status、create_time 查询时如何设计索引？"]',
 '["原则解释","失效场景","索引设计能力"]',
 'index,sql,explain', 1),

('mysql-transaction-isolation', 'MySQL', 'medium', 'MySQL 的事务隔离级别有哪些？InnoDB 默认隔离级别解决了哪些问题？',
 '["读未提交","读已提交","可重复读","串行化","InnoDB 默认可重复读","MVCC","next-key lock 缓解幻读"]',
 '["认为可重复读天然完全消除所有幻读","不会解释 MVCC","混淆脏读不可重复读幻读"]',
 '["可重复读和读已提交在 MVCC 上有什么区别？","当前读和快照读有什么区别？"]',
 '["库存扣减场景应该只依赖快照读吗？"]',
 '["隔离级别","MVCC 理解","锁和场景"]',
 'transaction,mvcc,lock', 1),

('mysql-mvcc', 'MySQL', 'hard', 'MVCC 是什么？InnoDB 如何通过 MVCC 实现快照读？',
 '["多版本并发控制","undo log","read view","trx_id","可见性判断","快照读不加锁"]',
 '["只说多版本不讲 read view","不知道 undo log 作用","混淆快照读和当前读"]',
 '["ReadView 里有哪些关键字段？","为什么快照读不阻塞写？"]',
 '["长事务会对 undo log 和系统造成什么影响？"]',
 '["机制完整性","关键字段","并发影响"]',
 'transaction,mvcc,undo-log', 1),

('mysql-explain', 'MySQL', 'easy', '你会如何使用 explain 分析一条 SQL？重点看哪些字段？',
 '["type","key","rows","Extra","possible_keys","Using filesort","Using temporary"]',
 '["只看是否用了索引","不知道 type 的含义","忽略 rows 和 Extra"]',
 '["type=ALL 代表什么？","Using filesort 一定很糟糕吗？"]',
 '["线上慢查询你会按什么顺序排查？"]',
 '["字段理解","排查顺序","优化意识"]',
 'sql,explain,optimization', 1),

('redis-cache-consistency', 'Redis', 'medium', '缓存和数据库如何保持一致？常见方案有哪些？',
 '["先更新数据库再删除缓存","延迟双删","binlog/Canal 异步同步","最终一致性","根据业务选择一致性等级"]',
 '["先更新缓存再更新数据库","追求所有场景强一致","忽略失败重试"]',
 '["为什么通常是删除缓存而不是更新缓存？","删除缓存失败怎么办？"]',
 '["商品详情页修改价格后如何保证缓存最终一致？"]',
 '["方案准确性","失败处理","业务一致性意识"]',
 'cache,consistency,redis', 1),

('redis-cache-penetration', 'Redis', 'easy', '缓存穿透、缓存击穿、缓存雪崩分别是什么？如何解决？',
 '["穿透是查询不存在数据","击穿是热点 key 失效","雪崩是大量 key 同时失效","布隆过滤器","空值缓存","互斥锁","随机过期时间","限流降级"]',
 '["三个概念混淆","只说加缓存","不知道热点 key 保护"]',
 '["布隆过滤器有什么误判问题？","热点 key 失效时为什么要加互斥锁？"]',
 '["秒杀商品详情页突然成为热点，你怎么保护 Redis 和数据库？"]',
 '["概念区分","方案匹配","高并发意识"]',
 'cache,availability,redis', 1),

('redis-persistence', 'Redis', 'medium', 'Redis 的 RDB 和 AOF 有什么区别？如何选择？',
 '["RDB 是快照","AOF 记录写命令","RDB 恢复快但可能丢数据","AOF 数据更完整但文件更大","可混合使用"]',
 '["只背名词","不知道恢复和丢数据差异","忽略 rewrite"]',
 '["AOF rewrite 是什么？","为什么 RDB fork 可能带来压力？"]',
 '["对数据可靠性要求高的缓存场景如何配置持久化？"]',
 '["机制理解","可靠性权衡","运维意识"]',
 'redis,persistence,rdb,aof', 1),

('redis-distributed-lock', 'Redis', 'medium', '如何用 Redis 实现分布式锁？需要注意哪些问题？',
 '["SET NX EX","唯一 value","释放锁校验 value","Lua 脚本保证原子性","过期时间","锁续期问题"]',
 '["用 setnx 后单独 expire","释放锁不校验持有者","忽略业务超时"]',
 '["为什么释放锁要用 Lua？","业务执行超过锁过期时间怎么办？"]',
 '["防止重复提交或库存扣减时如何设计锁？"]',
 '["原子性","安全释放","超时处理"]',
 'redis,lock,distributed', 1),

('redis-eviction', 'Redis', 'easy', 'Redis 内存淘汰策略有哪些？实际项目中怎么选择？',
 '["noeviction","volatile-lru","allkeys-lru","volatile-ttl","lfu","根据缓存场景选择 allkeys-lru/lfu"]',
 '["不知道 noeviction 行为","认为 Redis 会自动无限扩容","不区分 volatile 和 allkeys"]',
 '["maxmemory 设置后写入会怎样？","LRU 和 LFU 适合什么场景？"]',
 '["热点数据访问明显不均匀时选什么策略？"]',
 '["策略理解","场景选择","容量意识"]',
 'redis,memory,eviction', 1),

('spring-ioc-aop', 'Spring', 'medium', 'Spring IoC 和 AOP 分别解决什么问题？',
 '["IoC 管理对象创建和依赖","DI 注入依赖","AOP 处理横切逻辑","动态代理","事务/日志/权限是典型场景"]',
 '["只说控制反转不举例","把 AOP 当成继承","不知道代理限制"]',
 '["Spring AOP 和 AspectJ 有什么区别？","同类方法内部调用事务为什么可能失效？"]',
 '["你会把哪些逻辑做成 AOP？哪些不适合？"]',
 '["概念准确性","代理机制","工程场景"]',
 'spring,ioc,aop', 1),

('spring-bean-lifecycle', 'Spring', 'medium', 'Spring Bean 的生命周期大致是什么？',
 '["实例化","属性注入","Aware 回调","BeanPostProcessor","初始化方法","可用","销毁"]',
 '["只说创建和销毁","不知道 BeanPostProcessor","忽略单例和原型差异"]',
 '["BeanPostProcessor 可以做什么？","单例 Bean 和原型 Bean 销毁有什么区别？"]',
 '["你如何在项目启动时预加载配置或缓存？"]',
 '["流程完整性","扩展点理解","实际应用"]',
 'spring,bean,lifecycle', 1),

('spring-transaction', 'Spring', 'medium', 'Spring 事务失效的常见原因有哪些？',
 '["方法非 public","同类内部调用","异常被捕获","异常类型不匹配","数据库引擎不支持事务","未被 Spring 管理"]',
 '["只说加 @Transactional","不知道代理机制","忽略 rollbackFor"]',
 '["为什么同类内部调用会失效？","try-catch 吞掉异常会怎样？"]',
 '["下单接口扣库存和写订单如何保证事务？"]',
 '["代理机制","回滚规则","场景设计"]',
 'spring,transaction,aop', 1),

('springboot-autoconfiguration', 'Spring', 'medium', 'Spring Boot 自动配置的基本原理是什么？',
 '["约定大于配置","AutoConfiguration","条件注解","starter","配置属性绑定"]',
 '["只说省配置","不知道条件注解","不了解 starter 作用"]',
 '["ConditionalOnMissingBean 有什么作用？","自定义 starter 大致怎么做？"]',
 '["项目中如何按环境切换不同实现？"]',
 '["自动配置机制","条件装配","工程扩展"]',
 'springboot,autoconfiguration,starter', 1),

('spring-mvc-flow', 'Spring', 'easy', 'Spring MVC 一次请求的大致处理流程是什么？',
 '["DispatcherServlet","HandlerMapping","HandlerAdapter","Controller","View/ResponseBody","拦截器"]',
 '["只知道 Controller","不知道 DispatcherServlet","混淆 Filter 和 Interceptor"]',
 '["Filter 和 Interceptor 有什么区别？","参数校验在哪个阶段发生？"]',
 '["如何统一处理接口异常和返回结构？"]',
 '["请求链路","核心组件","扩展点"]',
 'springmvc,web,request-flow', 1)
ON DUPLICATE KEY UPDATE
    module = VALUES(module),
    difficulty = VALUES(difficulty),
    main_question = VALUES(main_question),
    key_points = VALUES(key_points),
    common_mistakes = VALUES(common_mistakes),
    followups = VALUES(followups),
    scenario_followups = VALUES(scenario_followups),
    scoring_rubric = VALUES(scoring_rubric),
    tags = VALUES(tags),
    enabled = VALUES(enabled);
